CC = wcl386
CFLAGS = -zq -wx -bt=nt -l=nt -i=..\fidoconfig;..\smapi;
COPT = -oneatx -5
LIB = wlib
LIBS = ..\smapi\smapiwcw.lib ..\fidoconfig\fidoconfig.lib

OBJS = sqpack.obj

.c.obj:
        $(CC) $(CFLAGS) $(COPT) -c $<

all:    $(OBJS) sqpack.exe

sqpack.exe:
        $(CC) $(CFLAGS) $(COPT) $(OBJS) $(LIBS)

clean:
        del *.exe *.obj *.bak *.lib
