CC      = wcc386
LINK    = WLINK

CFLAGS  = -i=.. -oneatx -zq -bt=os2v2 -DOS2 -DNOSEMAPHORES
LFLAGS  = system os2v2

all: sqpack.exe

sqpack.obj : sqpack.c
  @echo compiling sqpack
  $(CC) $(CFLAGS) sqpack.c

sqpack.exe: sqpack.obj
  @echo linking sqpack
  $(LINK) $(LFLAGS) FILE sqpack.obj Library ..\smapi\smapiwco.lib, ..\fidoconf\fconfwco.lib NAME sqpack.exe

clean:
	del *.bak
	del *.obj

distclean: clean
	del *.exe
