CC   = bcc
COPT = -O2 -DMSDOS -DINTEL -I.. -I../smapi -I../fidoconf -w -ml -DNOSEMAPHORES
LOPT =

all : sqpack.exe

sqpack.exe: sqpack.c
	$(CC) $(COPT) $(LOPT) sqpack.c ../fidoconf/fconfbcd.lib ../smapi/smapibcd.lib

clean:
	-del *.bak
	-del *.obj

distclean: clean
	-del sqpack.exe
