# makefile for EMX 0.9d with dynamic linkage
# legacy makefile, no support for the Husky build environment


CC   = gcc

COPT = -fomit-frame-pointer -fstrength-reduce -Zcrtdll -Wall -O2 -DOS2 -I..
LOPT = -L../smapi -L../fidoconf

all : sqpack.exe 

sqpack.exe: sqpack.c
	$(CC) $(COPT) $(LOPT) sqpack.c -o sqpack.exe  -lfconfemx -lsmapiemx


clean: 
	-del *.o

distclean: clean
	-del sqpack.exe

