# makefile for PGCC/EMX 1.1.1
# legacy makefile, no support for the Husky build environment


CC   = gcc

COPT = -fomit-frame-pointer -fstrength-reduce -Zomf -Zsys -Wall -O2 -DOS2 -I.. -DINTEL 
LOPT = -L../smapi -L../fidoconf -Zlinker /PM:VIO -s

all : sqpack.exe 

sqpack.exe: sqpack.c
	$(CC) $(COPT) $(LOPT) sqpack.c -o sqpack.exe -lfconfemo -lsmapiemo 


clean: 
	-del *.obj

distclean: clean
	-del sqpack.exe

