CC   = bcc
COPT = -O2 -DOS2  -DINTEL -I.. -I../smapi -I../fidoconf -w -DNOSEMAPHORES
LOPT =

all : sqpack.exe

sqpack.exe: sqpack.c
	$(CC) $(COPT) $(LOPT) sqpack.c ../fidoconf/fconfbco.lib	../smapi/smapibco.lib

clean:
	-del *.bak
	-del *.obj

distclean: clean
	-del sqpack.exe
