# legacy makefile for build with mingw-32 win32 target

CC=gcc
RM=del

CDEFS	= 
CFLAGS	= -Wall -I./h -I../huskylib -I../smapi -I../fidoconf -O3 
COPT	= -c

LFLAGS=-L../smapi -L../fidoconf
#LIBS=-lfidoconfigmgw -lsmapimgw
LIBS	= ../fidoconf/fidoconf.dll ../smapi/make/smapi.dll ../huskylib/make/husky.dll


default: all

TARGET=sqpack.exe

all: $(TARGET)

%.exe: %.c
	$(CC) $(CDEFS) $(CFLAGS) $(LFLAGS)  $^ -o $@ $(LIBS)

clean:
	-$(RM) *.o

distclean:
	-$(RM) $(TARGET)
