# Generic makefile to build sqpack on unix-like system

CC   = cc
COPT = -O2 -D__UNIX__ -I..
LOPT = -L../fidoconf
LIBS = -lfidoconfigqnx

all : sqpack 

sqpack: sqpack.c
	$(CC) $(COPT) $(LOPT) $^ -o $@ $(LIBS)

sqpack.1.gz : sqpack.1
	gzip -c sqpack.1 > sqpack.1.gz

clean: 
	-rm sqpack.1.gz

distclean: clean
	-rm sqpack
