# makefile for DJGPP gcc for DOS/DPMI
# legacy makefile, no support for the Husky build environment


CC   = gcc

CINCL= -I../fidoconf -I../smapi -I../huskylib

COPT = -fomit-frame-pointer -fstrength-reduce -Wall -O3 -I.. -mcpu=i486
LOPT = 
LIBS = ../fidoconf/fconfdjg.a ../smapi/make/smapidjg.a ../huskylib/make/huskydjg.a

all : sqpack.exe

sqpack.exe: sqpack.c
	$(CC) $(CINCL) $(COPT) $^ -o $@

clean:
	-del *.obj

distclean: clean
	-del sqpack.exe

