# $Id$
# Microsoft Visual C++ Makefile for build static library

CC=     cl
CFLAGS= -nologo -Zp1 -I.. -Ih
CDEFS=  -__NT__ -DWIN32 -D_CONSOLE
COPT=   -O2
TLIB=   lib -nologo

SMAPIL=	..\smapi\smapimvc.lib
FCONFL=	..\fidoconf\fconfmvc.lib

all: sqpack.exe

sqpack.exe:
        $(CC) $(CFLAGS) $(CDEFS) $(COPT) -Fe$@ sqpack.c $(FCONFL) $(SMAPIL)

clean:
	-del *.obj

distclean: clean
	-del *.exe
