# Legacy makefile to build sqpack on Linux

CC   = gcc
COPT = -O3 -I..
LOPT = -L../fidoconf -L../smapi
LIBS = -lfidoconfiglnx -lsmapilnx 

all : sqpack 

sqpack: sqpack.c
	$(CC) $(COPT) $(LOPT) $^ -o $@ $(LIBS)

sqpack.1.gz : sqpack.1
	gzip -c sqpack.1 > sqpack.1.gz

clean: 
	-rm sqpack.1.gz

distclean: clean
	-rm sqpack
