# $Id$
# Legacy makefile for Cygwin
# Usage:
# make -f makefile.cyg

CC      = gcc
COPT=-c -O3 -I. -I.. -Wall -pedantic -mno-cygwin
LFLAGS=-mno-cygwin

LINKSMAPI=../smapi/libsmapicyg.a
LINKFIDOC=../fidoconf/libfidoconfigcyg.a

all : sqpack.exe

sqpack.o: sqpack.c
	$(CC) $(COPT) sqpack.c -o sqpack.o

sqpack.exe: sqpack.o
	$(CC) $(LFLAGS) -o sqpack.exe sqpack.o ../smapi/patmat.o $(LINKSMAPI) $(LINKFIDOC)

clean:
	-rm -f *.o
	-rm *~

distclean: clean
	-rm sqpack.exe
