# makefile for EMX 0.9d with dynamic linkage
# legacy makefile, no support for the Husky build environment


CC   = gcc

COPT = -fomit-frame-pointer -fstrength-reduce -Zcrtdll -Wall -O2 -I..
LOPT = -L../smapi -L../fidoconf
LIBS = -lfconfemx -lsmapiemx

all : sqpack.exe 

sqpack.exe: sqpack.c
	$(CC) $(COPT) $(LOPT) $^ -o $@ $(LIBS)


clean: 
	-del *.o

distclean: clean
	-del sqpack.exe
