.TH SQPACK 1 "sqpack (v0.9)"
.SH NAME
sqpack \- purges squish msgbases taken from fidoconfig 
.SH SYNTAX
.TP
.B Purge areas
sqpack
.SH DESCRIPTION
SqPack takes the information about squish msgbases from fidoconfig and purges
the msgbases according to the -m and -p statements. See fidoconfig then.
.SH BUGS
If purging according to -p there goes something wrong and not all old mails
are purged.
The memory requirements are very high. There seems to be a memory leak.
Please report me, if you find any other.
hint: if there is a core files after first tries to run sqpack - don't worry!
Just edit /etc/fido/config. 99% of troubles comes from a wrong config file.
After that  please call tparser of the fidonet package to check your
config.
.SH AUTHOR
Matthias Tichy (mtt@uni-paderborn.de).
