.TH SQPACK 1 "sqpack (v1.0.2)"
.SH NAME
sqpack \- purges squish msgbases taken from fidoconfig 
.SH SYNTAX
.TP
.B Purge areas
sqpack
.SH DESCRIPTION
sqPack takes the information about squish msgbases from fidoconfig and purges
the msgbases according to the -m and -p statements. See fidoconfig.
.SH BUGS
hint: if there is a core files after first tries to run sqpack - don't worry!
Just edit /etc/fido/config. 99% of troubles comes from a wrong config file.
After that  please call tparser of the fidonet package to check your
config.
.SH AUTHOR
Matthias Tichy (mtt@tichy.de).
